### ISSUE TITLE
Add Directories and Environment Instructions

### ISSUE THREAD

**Issue by AkashM398** [Code-Sampler/Twilio_Examples#1]
Create Directories for Java, Python, Nodejs, etc.

**Comment by kartikver15gr8** [comment]
Hey @AkashM398 can u tell what exactly we need to do in this project I want to contribute to this!!

**Comment by AkashM398** [comment]
Hey @kartikver15gr8 currently I am simply testing this to organise this for my team internally. This repo is not open for all to contribute. Sorry about that!

**Comment by kartikver15gr8** [comment]
Its Okay @AkashM398 
Thanks for letting me know!
